---
baseURL: https://www.comprendrenotreepoque.org
languageCode: fr-fr
title: Comprendre notre époque
DefaultContentLanguage: fr
theme: hugo-universal-theme
MetaDataFormat: yaml
taxonomies:
  type: types
params:
  date_format: January 2, 2006
  email: regisphilibert@gmail.com
  logo: img/logo_cne_text.png
  logo_small: img/logo_cne_text.png
  topbar:
    enable: true
    text: "<a style='color:white;text-decoration:none;' href='mailto:comprendre.notre.epoque@orange.fr'>comprendre.notre.epoque@orange.fr</a>"
  carousel:
    enable: false
  see_more:
    enable: true
    subtitle: En quoi les sciences humaines et sociales peuvent-elles nous permettre
      de mieux comprendre et vivre ensemble notre époque ?
    link_url: "/definitions"
    link_text: Définitions des Sciences humaines et sociales pour les nuls
  style: blue
languages:
  fr:
    languageName: Français
menu:
  main:
  - url: https://www.comprendrenotreepoque.org/videos/la-psychologie-positive-peut-elle-faire-notre-bonheur/
    name: Événements Filmés
    weight: 1
  - url: "/evenements/"
    name: Évènements
    weight: 5
  - url: "/videos/"
    name: Vidéos
    weight: 4
  - url: "/livres/"
    name: Livres
    weight: 3
  topbar:
  - pre: "<i class='fa fa-2x fa-facebook'></i>"
    url: http://facebook.com
    name: Facebook
    weight: 1
  - pre: "<i class='fa fa-2x fa-youtube'></i>"
    url: https://www.youtube.com/channel/UC8IbYJEZKPY3TpCsY6unE2w
    name: Youtube
    weight: 2
