---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Contenu
- type: directory
  path: content
  label: Pages
  create: documents
  match: "*.md"
  templates:
  - page
- type: directory
  path: content/livres
  label: Livres
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - livre
- type: directory
  path: content/videos
  label: Videos
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - video
- type: directory
  path: content/evenements
  label: Evenements
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - evenement
- type: heading
  label: Autres
- type: document
  path: data/options.yaml
  label: Options
  templates:
  - options
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.54.0
  preview_output_directory: public
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: '0.52'
